# Generated by Django 4.1.7 on 2023-04-30 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 8, 14, 8, 958250, tzinfo=datetime.timezone.utc)),
        ),
    ]
