# Generated by Django 4.1.7 on 2023-04-30 10:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 10, 52, 55, 605358, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CheckTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finded_question', models.PositiveBigIntegerField(default=0)),
                ('user_passed', models.BooleanField(default=False)),
                ('percentage', models.PositiveBigIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.test')),
            ],
        ),
        migrations.CreateModel(
            name='CheckQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(help_text='E.x: a ', max_length=1)),
                ('true_answer', models.CharField(help_text='E.x: a ', max_length=1)),
                ('is_true', models.BooleanField(default=False)),
                ('checktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.checktest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
