# Generated by Django 4.1.7 on 2023-04-30 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_test_end_date_checktest_checkquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checktest',
            old_name='finded_question',
            new_name='finded_questions',
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 11, 43, 36, 695427, tzinfo=datetime.timezone.utc)),
        ),
    ]
